### ISSUE TITLE
Bölüm Sonu Canavarından Gelen Üst Düzey İtem ile Rastgele Işınlanma

### ISSUE THREAD

**Issue by bekirberksenel** [Bil481Group5/dungeon#1]
### **The God of Death - The Sword of God and danger of death - Teleportation**

 **The God of Death**
- Kullanıcı doğu, batı, kuzey ve güney yönlerinden birine doğru hareket ederken rastgele ihtimalle üst düzey bir yaratık olan God of Death ile karşılaşacak. Kullanıcının bu yaratığı öldürebilmesi için saldırı gücü ve canı çok yüksek olmalı, dolayısıyla mücadeleyi kazanabilmesi için oyunda bir hayli ilerlemiş olması gerekmekte . Bu sebeple bölüm sonu canavarı olarak isimlendirildi.

 **The Sword of God ve Üst Düzey Etkileri**
- Bölüm sonu canavarı God of Death ile yapılan mücadelenin kazanılması durumunda oyunun en güçlü itemi olan üst düzey bir savaş kılıcı Sword of God elde edilecek. Kullanıcı bu üst düzey kılıcı aldıktan sonra oyundaki kılıçtan gelen üst düzey saldırı gücüyle diğer canlılarla ve yaratıklarla yaptığı mücadeleleri rahatlıkla kazanabilecek. Ancak kullanıcı bölüm sonu itemi Sword of God' ı alabilme başarısını gösterip God of Death' i öldürebilirse bir riskle karşılaşacak ve bu riskin farkında olacak. Bölüm sonu itemi Sword of God kılıcı çok güçlü bir silah olduğu için equip etme aşamasında yüzde 50 ihtimalle kullanıcının ölmesine sebep olabilecek. Bu sebeple bölüm sonu itemi olarak isimlendirildi. 
Ayrıca Sword of God equip edilebilme başarısı gösterilebilirse oyuna yeni büyü olan The God of Thunder eklenecek.

 **Işınlanma Komutunun Açılması ve Komutun Özellikleri**
- Bölüm sonu itemi Sword of God kılıcı equip edilebilirse kullanıcının bu üst düzey kılıcın etkisiyle doğu, batı, kuzey ve güney yönlerine rastgele adımlarla hareket edebilmesi için oluşturulan teleport commandi aktifleşecek ve bölüm sonu itemine sahip olan kullanıcı ışınlanma yetkisi kazanarak teleport commandi ile haritada rastgele seçilen doğu, batı kuzey veya güney yönlerinden birine rastgele adımlarla hareket edebilecek.

**Comment by cagdasgerede** [comment]
Assign edilmemiş.

**Comment by bekirberksenel** [comment]
Düzenlendi

**Comment by bekirberksenel** [comment]
güncellendi
