### ISSUE TITLE
New Item: Goat Wool For Healing

### ISSUE THREAD

**Issue by TolgaAcar** [Bil481Group5/dungeon#3]
A hero can heal himself with eating and spells. However, in real life they will not heal you. I want to add a bandage-made from goat wool- to dress a wound. 

-  Hero can shear a goat with "shear" command for gather its wool.
-  After gathering the wool, hero can bandage his wound with "wear" command.

**Comment by cagdasgerede** [comment]
Bu tarif yetersiz. Ne yapacağını anlamadım. Başlığın da düzeltilmesi lazım.
