### ISSUE TITLE
Super Human Powers

### ISSUE THREAD

**Issue by kurular4** [Bil481Group5/dungeon#4]
We will have a new kind of item called magic mushroom and we distributed this item to the random points of map. When the character walks around, he may encounter the new item and if he wants he can use it to obtain its good effects. There will be new effect called super effect. The positive effects are health renewal and attack power increment. But the hero also may face the side effects of the item which are force-to-long-sleep and health reduction. The positive effect "extra damage" lasts for a limited time. Also, the old potions are removed to avoid excessive power.

**Comment by cagdasgerede** [comment]
Assign edilmemiş.

**Comment by kurular4** [comment]
updated for little changes.
